### ISSUE TITLE
IMFTrackFileReader issue checking SoundFieldGroupLabelSubDescriptor

### ISSUE THREAD

**Issue by IMFTool** [Netflix/photon#138]
IMFTrackFileReader complains about missing items in the SoundFieldGroupLabelSubDescriptor, but all of the items are optional as defined in ST 377-4:

ERROR-IMF Essence Component check: WaveAudioEssenceDescriptor in the IMFTrackFile represented by ID 4f45ea32-547d-458b-8b9c-66ea98ec72bc refers to a SoundFieldGroupLabelSubDescriptor that **is missing one/all of MCATitle, MCATitleVersion, MCAAudioContentKind, MCAAudioElementKind,**

**Comment by schakrovorthy** [comment]
As per st2067-2:2016 Section 5.3.6.5 Item Constraints - these items "shall be" present in the SoundFieldGroupLabelSubDescriptors. 

Quoting st2067-2:2016 "The keywords "shall" and "shall not" indicate requirements strictly to be followed in order to conform to the document and from which no deviation is permitted."

**Comment by IMFTool** [comment]
Thanks, agreed.
