### ISSUE TITLE
Interlaced MXF

### ISSUE THREAD

**Issue by SuperFish2016** [Netflix/photon#143]
Hi guys, i  would like to know if photon support interlaced  IMP check?
I created a interlaced package, there are several errors when  i used photon to check.
The "SampleRate" in EssenceDescriptor is 60000/1001 and the EditRate in MainImageSequence is 30000 10001.
The following is from Photon.
06 Nov 2016 16:33:00,587 [ERROR] [IMPAnalyzer]: 		ERROR-This Composition represented by the ID 322d1f36-7d1d-47da-beb4-fd8e08bdd171 is invalid since the VirtualTrack represented by ID 54743e99-5162-41ef-90c9-d8bf26f0b610 has a Resource represented by ID urn:uuid:8620a1cb-451d-44ef-b1d4-af030ae771fb that refers to a EssenceDescriptor in the CPL's EssenceDescriptorList represented by the ID urn:uuid:0cd5fcf8-5c3e-4ba0-b13e-baa07a212265 whose indicated SampleRate value is =================== EditRate =====================
numerator = 60000, denominator = 1001
, however the Resource Edit Rate is =================== EditRate =====================
numerator = 30000, denominator = 1001

According to the SMPTE ST 377-1:2011 (G.2.2 Sample Rate and Edit Rate)
Edit Rate shall equal the desired editing rate of the image data for the application. A commonly used Edit Unit
(i.e. 1/Edit Rate) is 1 image, but may be smaller or larger in some applications.
Note 1: For example, **the sampled image may be field based, but the editing may be frame based. In this case the Edit Rate will be half the Sample Rate.**

**Comment by svenkatrav** [comment]
Photon has support for interlaced IMPs conforming to Application#2(ST 2067-20) but we have done very limited test w.r.t interlace IMPs. As you pointed out in your analysis, Photon is not accounting for interlace case when validating track edit rate against the image sample rate. Do you see any other errors with interlace IMP? Could you please attach CPL here? This will help us validating the fix for this issue. Thanks.

**Comment by SuperFish2016** [comment]
[CPL_interlaced_test.txt](https://github.com/Netflix/photon/files/577743/CPL_interlaced_test.txt)
please change the suffix ".txt" to ".zip" after you download it.

**Comment by svenkatrav** [comment]
Thanks for sharing the CPL. We have fixed the interlace sample rate vs edit rate issue with 4.1.2 version of Photon. There are still 2 errors seen with CPL you shared:

1. ERROR-Segment represented by the Id urn:uuid:7e722ffb-8368-4ca9-9a28-bd1480effb73 in the Composition represented by ID edef2ee4-645e-4fb1-9e0f-2b281ff4c9e7 has a sequence represented by ID urn:uuid:32114b51-5be1-4b4a-89d2-f73fbfa4d775, whose duration represented in Composition Edit Units is (9315.999625) is not an integer

**This error is due to below requirement in 2067-3-2016 section 7.3 
The duration of a Sequence shall be the sum of the duration of its Resources and shall be an integer number of Composition Edit Units.**

2. ERROR-EssenceDescriptor with ID 10957c2e-bce0-4e7f-8c7f-3c9bfc5a957f has invalid ColorPrimaries(P3D65)-TransferCharacteristic(SMPTEST2084)-CodingEquation(ITU709) combination in Image Essence Descriptor
**This is because COLOR6 is only supported with RGB color components as per table-3 2067-21-2016.**

**Comment by SuperFish2016** [comment]
Thanks for your quick reply, I have a question about the sequence duration ERROR.
Consider this:
CPL EditRate: 30000/1001 (Only have one video resource and audio resource in the CPL)
Video Resource duration: 9
Since the audio resource need have the same duration with the video in the CPL.
That means: (audio duration *30000 / 1001) / 48000 = 9. 
Here is my question: I can not find a valid audio duration(integer) to make  this equation true.

In the attached CPL
Video duration is 9316 and  audio duration  is 14920505.
Photon has calculation the duration (represented in CPL EditRate) as following:
14920505 * 30000 / 1001 / 48000 = 9315.999625.
It seems that there is no valid integer can make the result to be 9316.
So ,Photon will always report that ERROR. I thinks this may be a bug. Please check it.

**Comment by palemieux** [comment]
> Here is my question: I can not find a valid audio duration(integer) to make this equation true.

As specified in ST 2067-20, _if the average number of audio samples per Composition Edit Unit is not an integer, the duration of each Segment shall be an integer multiple of 5/Composition Edit Rate_
