### ISSUE TITLE
"Segment duration is not integer" an error

### ISSUE THREAD

**Issue by cfadamp** [Netflix/photon#160]
Dear developers,

we have a strange error message for a 59.94 IMP. Please see the full error message below. Attached is problematic CPL xml (I had to change the extension to txt from xml). We think that this is a false error message, let us know what you think please.

Photon library v4.1.0 (Oct 18 2016)

[INFO ] [Composition]: CompositionPlaylist Document has 2 errors and 0 warnings
[ERROR] [Composition]: ERROR-Segment represented by the Id urn:uuid:8c4e7d33-31bd-451d-bd32-a85f967d5b3a in the Composition represented by ID 0c30983b-4296-4bf4-9490-975c9ef22a3f has a sequence represented by ID urn:uuid:f647c847-890b-4270-984e-9e9e12a3c741, whose duration represented in Composition Edit Units is (43092.000500) is not an integer
[ERROR] [Composition]: ERROR-Segment represented by the Id urn:uuid:8c4e7d33-31bd-451d-bd32-a85f967d5b3a in the Composition represented by ID 0c30983b-4296-4bf4-9490-975c9ef22a3f has a sequence represented by ID urn:uuid:42e88dcb-b0e6-466f-988e-6f4289709d59, whose duration represented in Composition Edit Units is (43092.000500) is not an integer

Best,
Adam Pongracz
[CPL.txt](https://github.com/Netflix/photon/files/608999/CPL.txt)

**Comment by palemieux** [comment]
The duration of all Sequences within a Segment *shall* be identical.

As a result, a Main Image Sequence of 39 frames at 60000/1001 fps is not possible in App 2 since `39 * 1001/60000` cannot be expressed as an integer number of audio edit units (1/48000). 

At 60000/1001 fps,  the duration of each Segment must therefore be an integer multiple of 5/Composition Edit Rate.

See Section 7.4 at ST 2067-20 and #143
